### ISSUE TITLE
Add pagination with Pagy

### ISSUE THREAD

**Issue by excid3** [excid3/beginnerbounties.com#10]
The [pagy gem](https://github.com/ddnexus/pagy) is an excellent gem for adding pagination. Let's add pagination to the Bounties and Users::Bounties controllers using pagy. 

- [ ] Paginate the Bounties index
- [ ] Paginate the Users::Bounties index

This project has a $20 bounty.

**Comment by youngbloodcyb** [comment]
@excid3  I would love to take on this one! I'm pretty beginner, so it may take me a bit. Is that okay?

**Comment by nnahgodspower122** [comment]
Hi @excid3, I have learnt about pagy gem and would love to put that knowledge into practice, I would be completing the task within a short period of time.
Thanks

**Comment by deyemiobaa** [comment]
I'd be happy to take on this issue. I've used the pagy gem in a couple of projects and I can get this done quickly

**Comment by excid3** [comment]
@youngbloodcyb since you were first, I'll give it to you.
Join our Discord if you need any help along the way! https://discord.gg/gorails

If he doesn't get to it or wants to pass it on, we'll let the next person tackle it. 👍

**Comment by youngbloodcyb** [comment]
@excid3 Awesome, thank you! I should finish it by tonight 👍🏼
