### ISSUE TITLE
Direct object reference

### ISSUE THREAD

**Issue by gregmolnar** [excid3/beginnerbounties.com#13]
https://github.com/excid3/beginnerbounties.com/blob/main/app/controllers/users/bounties_controller.rb#L56
I can create a bounty in someone else's account by setting the user_id to theirs. `user_id` should be removed from the permitted params.

**Comment by excid3** [comment]
And this is why we don't use scaffolds, kids!

**Comment by gregmolnar** [comment]
We could handle this in Rails. The scaffold generator should leave out any belongs_to attribute from the permit list. 
I might look into that when I have some time.

**Comment by excid3** [comment]
It might be tricky because a model could belongs_to multiple models and I'm not sure how you'd know unless there was a flag.

I've definitely wanted a scoped scaffold generator like `--scoped current_user` which would remove the `user_id` and also scope the index and `set_resource` methods.

**Comment by gregmolnar** [comment]
When you call the generator like this:
```
rails g scaffold bounty belongs_to:user ....
```
It is pushed into the attribute_names here: https://github.com/rails/rails/blob/98b2e8a4968827beb6460174c3caf13a33487921/railties/lib/rails/generators/named_base.rb#L188
and it is possible to check there is the attribute is a belongs_to. 
So instead of relying on the attribute_names generated here, the scaffold_controller generator could just loop over the objects and skip the belongs_to ones.

**Comment by gregmolnar** [comment]
And as for it can belong_to multiple models, I think here we should approach a whitelist rather than blacklist approach and just discard all belongs_to associations, because those are likely to lead to security issues.
