### ISSUE TITLE
Fix card overflow

### ISSUE THREAD

**Issue by mybuddyandrew** [excid3/beginnerbounties.com#17]
Fix card overflow.

![FqKjML3XoAE26nk](https://user-images.githubusercontent.com/39465527/222274160-b118080b-1512-4049-af19-9a0f8ada62b3.jpeg)

**Comment by deyemiobaa** [comment]
Hi @mybuddyandrew. I'd like to work on this

**Comment by mybuddyandrew** [comment]
Go for it!!

**Comment by deyemiobaa** [comment]
PR submitted #21

**Comment by excid3** [comment]
Fixed in #21

**Comment by excid3** [comment]
Great work @deyemiobaa 👍

**Comment by Ibnballo1** [comment]
@excid3  wouldn't it be nice to mark it as completed on the websites

**Comment by excid3** [comment]
@Ibnballo1 the author of the bounty is the one who can change the status.

We will need to add an admin area so I can update them if the author did not.

**Comment by Ibnballo1** [comment]
Alright @excid3  and please I am available for job if there is an open opportunity, thank you.
