### ISSUE TITLE
Create testing suite to improve maintainability

### ISSUE THREAD

**Issue by AhmadR-Coder-max** [excid3/beginnerbounties.com#34]
Hi,

I noticed that the code for this project does not currently have any automated tests (especially for models). As tests can help ensure the reliability and maintainability of the codebase, I suggest that we add some automated tests to the project.

I'd be happy to help with this effort, so please let me know if this is something that you'd be interested in pursuing.

Thanks!

**Comment by excid3** [comment]
Test suite and GitHub Actions are now implemented.  👍
