### ISSUE TITLE
Password reset emails do not send

### ISSUE THREAD

**Issue by pcai** [excid3/beginnerbounties.com#37]
Repro:
- navigate to https://beginnerbounties.com/users/password/new
- enter the email address of an existing user, then hit enter
- observe results

Expected:

Password reset email is sent.

Actual:

500 error page.
![image](https://user-images.githubusercontent.com/222655/228075573-365f2853-8cfc-4755-bb5c-8055250d90e9.jpeg)

Additional info:

I suspect a missing or incorrect mailer configuration. When I enter a dummy email address and submit, the page reloads with a validation error "email not found." So the exception only seems to happen when the email entered is actually registered.

**Comment by excid3** [comment]
Yeah, I haven't implemented a mail service yet. Still need to do that. 👍

**Comment by excid3** [comment]
Fixed!
