### ISSUE TITLE
http is available

### ISSUE THREAD

**Issue by Paprikas** [excid3/beginnerbounties.com#44]
Expecting redirect to https?
http://beginnerbounties.com/

**Comment by excid3** [comment]
Someone should add `config.force_ssl = true` to the production env. PR welcome.

**Comment by JuzerShakir** [comment]
I would like to take on this task... @excid3

**Comment by excid3** [comment]
It's all yours @JuzerShakir 👍

**Comment by JuzerShakir** [comment]
Thanks @excid3! :smile: I do have an existing PR open for [GitHub Actions CI](https://github.com/excid3/beginnerbounties.com/pull/24). Therefore, I will not be able to open a new PR for this. Would you like me to add this change in GitHub Actions CI PR?

**Comment by excid3** [comment]
Use a different branch to create a separate PR
