### ISSUE TITLE
Hide content if there are no bounties to show

### ISSUE THREAD

**Issue by JuzerShakir** [excid3/beginnerbounties.com#51]
![Screenshot from 2023-09-21 09-45-14](https://github.com/excid3/beginnerbounties.com/assets/10782481/84ab6177-9c0e-47e9-97ae-6a9078b914d0)

- **I would like to hide the title & pagination from the homepage if there are no bounties to show** which would look something like this...

![Screenshot from 2023-09-21 10-21-35](https://github.com/excid3/beginnerbounties.com/assets/10782481/f65f1481-a6e8-4a34-9313-0451f34df9a3)

We could just keep it like this but we would need to somehow convey the message to the user that there are no bounties to show currently at this time and if there are any bounties available, they would show up here. 

For that, I have a couple of ideas. Either we could add a simple text or to make it look pretty add an SVG image.

Thoughts?

**Comment by luffy-web-dev** [comment]
Add text to look pretty using good css.It will make good show.

**Comment by JuzerShakir** [comment]
Yes @luffy-web-dev, I am leaning toward that too, it's better. I think an SVG would be an overkill!

**Comment by JuzerShakir** [comment]
![Screenshot from 2023-09-21 14-41-33](https://github.com/excid3/beginnerbounties.com/assets/10782481/ca247ed4-b094-4823-bd21-a351694b9beb)

Thoughts?
