### ISSUE TITLE
Show only Open Bounties by default

### ISSUE THREAD

**Issue by excid3** [excid3/beginnerbounties.com#66]
Most people visiting Beginner Bounties are looking for open bounties. We should update the index to show only the Open Bounties by default.

If there are no Open Bounties, we should probably display a message saying something like this:

> There are no open bounties right now. Spread the word that we need people to post new Beginner Bounties!

@JuzerShakir want to do this one?

**Comment by JuzerShakir** [comment]
Yes! @excid3

**Comment by excid3** [comment]
Thanks a bunch! 💪

**Comment by JuzerShakir** [comment]
Here's the [PR](https://github.com/excid3/beginnerbounties.com/pull/68) for this issue @excid3.
