### ISSUE TITLE
Sign up button should have a more prominent style

### ISSUE THREAD

**Issue by radar** [excid3/beginnerbounties.com#7]
<img width="347" alt="image" src="https://user-images.githubusercontent.com/2687/222257917-19c80881-b341-4982-b01f-726fd29f4dcd.png">

**Comment by edith007** [comment]
Hi @radar 👋🏻 Can I work on this issue 🙏🏻 🙇🏻

**Comment by excid3** [comment]
@edith007 please do!

**Comment by edith007** [comment]
Thanks a ton @excid3 🙇🏻 
I was amazed by the tweet and really love the idea. I am really excited to work on this issue 😄

**Comment by usama20** [comment]
Hi @excid3  @radar I have made some changes in the login and sign up form if you like it I can make a PR for this
![image](https://user-images.githubusercontent.com/38781275/222272849-71169b03-5cd6-4085-b139-1659d23877d6.png)
![image](https://user-images.githubusercontent.com/38781275/222272943-cf97d64e-fb8f-4517-a3da-491f1fe96182.png)

**Comment by edith007** [comment]
@usama20 go for it 🚀

**Comment by saurav-codes** [comment]
But why didn't you update the status to assigned on bounty websites

**Comment by radar** [comment]
Status is now assigned.

**Comment by geekiedj** [comment]
Uh-oh I was going to work on the issue but it looks like someone's on it.

**Comment by aj-abhishek-jadav** [comment]
@radar I've already raised PR for same earlier. Not only for sign up buttons but labels as well for signup, login forgot password pages
Here's the PR - https://github.com/excid3/beginnerbounties.com/pull/29

**Comment by MarcRodrigFelix** [comment]
Hello, I am new here. So assigned means it's taken?

**Comment by radar** [comment]
indeed that is what it means

**Comment by Ibnballo1** [comment]
@radar 
How can we get new project to work on, please?
All projects on the website (begginnerbounties.com) have all be assigned and/ completed. Is there a way to get informed of new project?

Also, the Prev/Next button at the bottom of the page is not working

**Comment by ghost** [comment]
Hello, would be great to have a filter to split the assigned, completed and available bounties
would love to try and implement that

**Comment by lokeshk88** [comment]
Can u explain a bit , what u want for sign up button ?

**Comment by RacheliWiner** [comment]
is there any way to know when a new bounty is open?
maybe to get an email for subscribers?
thanks!
