### ISSUE TITLE
Add A Twitter Card to Beginner Bounties

### ISSUE THREAD

**Issue by siaw23** [excid3/beginnerbounties.com#8]
There's currently some Open Graph, but no Twitter Card. Please add a Twitter Card so links on Twitter look great! ✨

**Comment by excid3** [comment]
Agreed!

**Comment by Eazybright** [comment]
I would love to work on this

**Comment by siaw23** [comment]
Go for it! @Eazybright

**Comment by Eazybright** [comment]
PR opened: [https://github.com/excid3/beginnerbounties.com/pull/16](https://github.com/excid3/beginnerbounties.com/pull/16)

**Comment by siaw23** [comment]
Completed in: https://github.com/excid3/beginnerbounties.com/pull/16

**Comment by Ose-Augustine** [comment]
Is this still open?

**Comment by Eazybright** [comment]
> 

no it's closed

**Comment by captproton** [comment]
It's still posted at https://beginnerbounties.com/bounties/4

**Comment by excid3** [comment]
@siaw23 will need to mark it as complete. 👍
